server.port=8081
spring.application.name=Mi Negocio
spring.datasource.url=jdbc:postgresql://dpg-d07nttk9c44c73a5uodg-a.oregon-postgres.render.com:5432/alquimiasoft
spring.datasource.username=anderson
spring.datasource.password=gbZrKQrJgrwoM1dHKqw8BUrtwQlS0fUW
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Opcional Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml